const navData = [
  {
    title: "Men",
    type: [
      {
        title: "Topwear",
        categories: [
          "T-Shirts",
          "Casual Shirts",
          "Formal Shirts",
          "Sweatshirts",
          "Sweaters",
          "Jackets",
          "Blazers & Coats",
          "Suits",
          "Rain Jackets",
        ],
      },
      {
        title: "Indian & Festive Wear",
        categories: [
          "Kurtas & Kurta Sets",
          "Sherwanis",
          "Nehru Jackets",
          "Dhotis",
        ],
      },
      {
        title: "Bottomwear",
        categories: [
          "Jeans",
          "Casual Trousers",
          "Formal Trousers",
          "Shorts",
          "Track Pants & Joggers",
        ],
      },
      {
        title: "Innerwear & Sleepwear",
        categories: [
          "Briefs & Trunks",
          "Boxers",
          "Vests",
          "Sleepwear & Loungewear",
          "Thermals",
        ],
      },
      {
        title: "Footwear",
        categories: [
          "Casual Shoes",
          "Sports Shoes",
          "Formal Shoes",
          "Sneakers",
          "Sandals & Floaters",
          "Flip Flops",
          "Socks",
        ],
      },
      {
        title: "Sports & Active Wear",
        categories: [
          "Sports Shoes",
          "Sports Sandals",
          "Active T-Shirts",
          "Track Pants & Shorts",
          "Tracksuits",
          "Jackets & Sweatshirts",
          "Sports Accessories",
          "Swimwear",
        ],
      },
      {
        title: "Gadgets",
        categories: [
          "Smart Wearables",
          "Fitness Gadgets",
          "Headphones",
          "Speakers",
        ],
      },
      {
        title: "Fashion Accessories",
        categories: [
          "Wallets",
          "Belts",
          "Belts",
          "Perfumes & Body Mists",
          "Trimmers",
          "Deodorants",
          "Ties, Cufflinks & Pocket Squares",
          "Accessory Gift Sets",
          "Caps & Hats",
          "Mufflers, Scarves & Gloves",
          "Phone Cases",
          "Rings & Wristwear",
          "Helmets",
        ],
      },
    ],
  },
  {
    title: "Women",
    type: [
      {
        title: "Indian & Fusion Wear",
        categories: [
          "Kurtas & Suits",
          "Kurtis, Tunics & Tops",
          "Ethnic Wear",
          "Leggings, Salwars & Churidars",
          "Skirts & Palazzos",
          "Sarees",
          "Dress Materials",
          "Lehenga Cholis",
          "Dupattas & Shawls",
          "Jackets",
        ],
      },
      {
        title: " Western Wear",
        categories: [
          "Dresses",
          "Jumpsuits",
          "Tops",
          "Jeans",
          "Trousers & Capris",
          "Shorts & Skirts",
          "Shrugs",
          "Sweaters & Sweatshirts",
          "Jackets & Coats",
          "Blazers & Waistcoats",
        ],
      },
      {
        title: "Footwear",
        categories: [
          "Flats",
          "Casual Shoes",
          "Heels",
          "Boots",
          "Sports Shoes & Floaters",
        ],
      },

      {
        title: "Sports & Active Wear",
        categories: [
          "Clothing",
          "Footwear",
          "Sports Accessories",
          "Sports Equipment",
        ],
      },
      {
        title: "Lingerie & Sleepwear",
        categories: [
          "Bra",
          "Briefs",
          "Shapewear",
          "Sleepwear & Loungewear",
          "Swimwear",
          "Camisoles & Thermals",
        ],
      },
      {
        title: "Beauty & Personal Care",
        categories: [
          "Makeup",
          "Skincare",
          "Premium Beauty",
          "Lipsticks",
          "Fragrances",
        ],
      },
      {
        title: "Gadgets",
        categoris: [
          "Smart Wearables",
          "Fitness Gadgets",
          "Headphones",
          "Speakers",
        ],
      },
      {
        title: "Jewellery",
        categories: ["Fashion Jewellery", "Fine Jewellery", "Earrings"],
      },
    ],
  },
  {
    title: "Kids",
    type: [
      {
        title: "Boys Clothing",
        categories: [
          "T-Shirts",
          "Shirts",
          "Shorts",
          "Jeans",
          "Trousers",
          "Clothing Sets",
          "Ethnic Wear",
          "Track Pants & Pyjamas",
          "Jacket, Sweater & Sweatshirts",
          "Part Wear",
          "Innerwear & Thermals",
          "Nightwear & Loungewear",
          "Value Packs",
        ],
      },
      {
        title: "Girls Clothing",
        categories: [
          "Dresses",
          "Tshirts",
          "Tops",
          "Clothing Sets",
          "Dungarees & Jumpsuits",
          "Trousers & Capris",
          "Lehenga choli",
          "Shorts & Skirts",
          "Tights & Leggings",
          "Innerwear & Thermals",
          "Jacket, Sweater & Sweatshirts",
          "Nightwear & Loungewear",
          "Value Packs",
        ],
      },
      {
        title: "Footwear",
        categories: [
          "Flipflops",
          "Casual Shoes",
          "Sports Shoes",
          "Flats",
          "Sandals",
          "School Shoes",
          "Socks",
        ],
      },
      {
        title: "Toys",
        categories: [
          "Learning & Development",
          "Activity Toys",
          "Soft Toys",
          "Action Figure",
        ],
      },
      {
        title: "Infants",
        categories: [
          "Bodysuits",
          "Rompers & Sleepsuits",
          "Clothing Sets",
          "Tshirts & Tops",
          "Dresses",
          "Winter Wear",
          "Innerwear & Sleepwear",
          "Infant Care",
        ],
      },
      {
        title: "Kids Accessories",
        categories: [
          "Bags & Backpacks",
          "Watches",
          "Jewellery & Hair accessory",
          "Sunglasses",
          "Masks & Protective Gears",
          "Caps & Hats",
        ],
      },
      {
        title: "Brands",
        categoris: [
          "H&M",
          "Max Kids",
          "Pantaloons",
          "United Colors Of Benetton Kids",
          "YK",
          "U.S. Polo Assn. Kids",
          "Mothercare",
          "HRX",
        ],
      },
    ],
  },
  {
    title: "Home & Living",
    type: [
      {
        title: "Bed Linen & Furnishing",
        categories: [
          "Bedsheets",
          "Bedding Sets",
          "Blankets, Quilts & Dohars",
          "Pillows & Pillow Covers",
          "Bed Covers",
          "Diwan Sets",
          "Chair Pads & Covers",
          "Sofa Covers",
        ],
      },
      {
        title: "Flooring",
        categories: ["Carpets", "Floor Mats & Dhurries", "Door Mats"],
      },
      {
        title: "Bath",
        categories: [
          "Bath Towels",
          "Hand & Face Towels",
          "HeelBeach Towelss",
          "Towels Set",
          "Bath Rugs",
          "Bath Robes",
          "Bathroom Accessories",
        ],
      },
      {
        title: "Lamps & Lighting",
        categories: [
          "Floor Lamps",
          "Ceiling Lamps",
          "Table Lamps",
          "Wall Lamps",
          "Outdoor Lamps",
          "String Lights",
        ],
      },
      {
        title: "Home Décor",
        categories: [
          "Plants & Planters",
          "Aromas & Candles",
          "Clocks",
          "Mirrors",
          "Wall Décor",
          "Festive Decor",
          "Pooja Essentials",
          "Wall Shelves",
          "Fountains",
          "Showpieces & Vases",
        ],
      },
      {
        title: "Kitchen & Table",
        categories: [
          "Dinnerware & Serveware",
          "Cups and Mugs",
          "Bakeware & Cookware",
          "Kitchen Storage & Tools",
          "Bar & Drinkware",
          "Table Covers & Furnishings",
        ],
      },
      {
        title: "Storage",
        categoris: ["Organisers", "Hooks & Holders", "Laundry Bags"],
      },
      {
        title: "Brands",
        categories: [
          "Home Centre",
          "Spaces",
          "D'Decor",
          "Portico New York",
          "Story@Home",
          "Pure Home & Living",
          "Swayam",
          "Raymond Home",
          "Maspar",
          "Corelle",
          "Trident",
          "Cortina",
          "Random",
          "Ellementry",
          "ROMEE",
          "SEJ by Nisha Gupta",
        ],
      },
    ],
  },
  {
    title: "Beauty",
    type: [
      {
        title: "Makeup",
        categories: [
          "Lipstick",
          "Lip Gloss",
          "Lip Liner",
          "Mascara",
          "Eyeliner",
          "Kajal",
          "Eyeshadow",
          "Foundation",
          "Primer",
          "Concealer",
          "Compact",
          "Nail Polish",
        ],
      },
      {
        title: "Skincare, Bath & Body",
        categories: [
          "Face Moisturiser",
          "Cleanser",
          "Masks & Peel",
          "Sunscreen",
          "Serum",
          "Face Wash",
          "Eye Cream",
          "Lip Balm",
          "Body Lotion",
          "Body Wash",
          ,
          "Body Scrub",
          "Hand Cream",
        ],
      },
      {
        title: "Haircare",
        categories: [
          "Shampoo",
          "Conditioner",
          "Hair Cream",
          "Hair Oil",
          "Hair Color",
          "Hair Serum",
          "Hair Accessory",
        ],
      },
      {
        title: "Fragrances",
        categories: ["Perfume", "Deodorant", "Body Mist"],
      },
      {
        title: "Appliances",
        categories: ["Hair Straightener", "Hair Dryer", "Epilator"],
      },
      {
        title: "Men's Grooming",
        categories: ["Trimmers", "Beard Oil", "Hair Wax"],
      },
      {
        title: "Beauty Gift & Makeup Set",
        categoris: ["Beauty Gift", "Makeup Kit"],
      },
      {
        title: "Brands",
        categories: [
          "Lakme",
          "Maybelline",
          "LOreal",
          "Philips",
          "Bath & Body Works",
          "THE BODY SHOP",
          "Biotique",
          "Mamaearth",
          "MCaffeine",
          "Nivea",
          "Lotus Herbals",
          "LOreal Professionnel",
          "KAMA AYURVEDA",
          "M.A.C",
          "Forest Essentials",
        ],
      },
    ],
  },
];
export default navData;
